### PR TITLE
Expanding Pin chapter

### LINKED ISSUE #12: Pinning chapter would benefit from diagram
I'm trying to understand concretely how pinning works, especially in the context of `async`/`await!`, and I think that having an example with a diagram that shows exactly where everything is in memory would be extremely helpful.

I'd consider offering such a diagram, but I don't believe I grok the subject matter enough to produce one.

### PR DESCRIPTION
**Pull request by cfsamson**
Pinning seems to be a hard concept to explain and I've seen numerous questions about it lately. I've tried to give a correct and thorough explanation of it and thought I might contribute some of that work here if there is any interest. I've added new examples, a diagram and adapted it to fit with what was already written. I'm not sure if it gets too detailed, but I'll of course rework it based on feedback if there is any interest in that. 

This might also close #12 and #73.

### CODE REVIEW

**Comment by cfsamson** [comment]
The spellchecker doesn't like `PhantomPinned` and `init`. I guess at least `PhantomPinned` should be added to the dictionary but I'm unsure about the policy so I just leave this failing for now.

**Comment by nellshamrell** [comment]
Hi @cfsamson - is this still something you'd like to push forward? I think it's fine to add ```PhantomPinned``` to the dictionary, as well as ```init```

**Comment by cfsamson** [comment]
@nellshamrell Yeah, sure. I'll add them to the dictionary. I'm not sure what the next step after that would be though.

**Comment by cfsamson** [comment]
No problem. Thanks!

**Pull request merged**
