### PR TITLE
Add Async Recursion Macro to Workarounds

### PR DESCRIPTION
**Pull request by zicklag**
This may not be something you want in the book, but there is a nifty macro crate for automatically transforming async functions to return boxed futures that could be useful to people.

I noticed the other example was in a separate file, but this is a super small example so I just inlined it. I can change it if you like.

### CODE REVIEW

**Comment by taiki-e** [comment]
I wonder if this is no longer necessary because impl trait recursion was [allowed some time ago](https://github.com/rust-lang/rust/pull/94081/).

**Comment by zicklag** [comment]
Looks like a simple recursive async function still fails ( [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3dd0f3d14a08654a9c227f19a4dbcfd1) ).

**Comment by taiki-e** [comment]
Ah, thanks. And it is impressive that the compiler's diagnosis mentions async_recursion crate.
```
  = note: consider using the `async_recursion` crate: https://crates.io/crates/async_recursion
```

**Review by nrc — APPROVED** [review]
Thanks!

**Comment by nrc** [comment]
Given the age of the PR and the conflicts I'm going to close this, sorry it never got merged

**Pull request closed without merging**
