### PR TITLE
add the translation of zh-CN to the appendix

### PR DESCRIPTION
**Pull request by huangjj27**
I have updated the translation to the newest version of the async book of the English version, so I add it to the appendix

### CODE REVIEW

**Comment by huangjj27** [comment]
I rebase my master branch and clear the commits history. r?

**Comment by taiki-e** [comment]
Hmm, it seems there are at least two Simplified Chinese translations (https://github.com/rust-lang/async-book/pull/159, cc @playaround88).

Would it be possible to consider merging them? If that is not easy, I think it would be ok to link to both as [rust-lang/book has done in the past](https://github.com/rust-lang/book/issues/461#issuecomment-294210225).

In any case, it seems preferable to have an issue that tracks translations in each language.

**Comment by playaround88** [comment]
hi，#159，I have put my translation on my github page

**Comment by jiachao2130** [comment]
我去年翻译过一次，最近又重新跟上主线 commits 并修改了部分措词，确实需要一个组织来统筹接管这些事才好

https://suibianxiedianer.github.io/async-book/

**Comment by playaround88** [comment]
> 我去年翻译过一次，最近又重新跟上主线 commits 并修改了部分措词，确实需要一个组织来统筹接管这些事才好
> 
> https://suibianxiedianer.github.io/async-book/

统一你的观点，翻译之前，也没有看到有合并主干翻译
我那个翻译，主要是两点考虑
1、点击中文段落，可以查看英文，方便对照阅读
2、不修改原文，在合并主干变更时，理论上是可以保持更新

**Comment by huangjj27** [comment]
@playaround88  @jiachao2130 Hi, I find a plugin called `mdbook-i18n` from [mdbook i18n PR](https://github.com/rust-lang/mdBook/issues/5#issuecomment-1258922986) maybe help. Is it a good idea to re-construct our translation with this plugin? and create an organization (or contribute it to some community, like [rustcc](https://github.com/rustcc)) to do this?

**Comment by playaround88** [comment]
> @playaround88 @jiachao2130 Hi, I find a plugin called `mdbook-i18n` from [mdbook i18n PR](https://github.com/rust-lang/mdBook/issues/5#issuecomment-1258922986) maybe help. Is it a good idea to re-construct our translation with this plugin? and create an organization (or contribute it to some community, like [rustcc](https://github.com/rustcc)) to do this?

@huangjj27 thanks, that is good resolution，but this need author change the origin repo，and accept this suggestion.

**Comment by ziyouwa** [comment]
> 我去年翻译过一次，最近又重新跟上主线 commits 并修改了部分措词，确实需要一个组织来统筹接管这些事才好
> 
> https://suibianxiedianer.github.io/async-book/

比较了一下，还是您的翻译更准确些，多谢！希望能持续更新。

**Comment by nrc** [comment]
Hi, thanks for translating and sorry for no review for the PR. We're about to start a pretty fundamental rewrite, so I'm not going to add any more translations for now.

**Comment by huangjj27** [comment]
> We're about to start a pretty fundamental rewrite

It's great! I'll track on the new version.

**Pull request closed without merging**
