### PR TITLE
Fix running code

### PR DESCRIPTION
**Pull request by funkill**
Ignore running some code (like partial includes) and fix sending Rust edition to playground (#31)

### CODE REVIEW

**Comment by funkill** [comment]
Some ignored code can run if copy some uses or other code from rs-files to md-files

**Comment by cramertj** [comment]
Is it possible to use 2018 edition everywhere rather than annotating it on each block? There shouldn't be any 2015e blocks anywhere in the book.

**Comment by funkill** [comment]
No. Mdbook by default uses 2015 edition and changing it to 2018 possible only for individual blocks ([source code](https://github.com/rust-lang/mdBook/blob/master/src/theme/book.js#L111)). With current version of mdbook we must annotate each code block.

**Comment by funkill** [comment]
Some hours ago [opened PR](https://github.com/rust-lang/mdBook/pull/1100) in mdbook repo about setting 2018 edition globally. We can wait for accepting this PR.

**Comment by dunnock** [comment]
@funkill it seems it will take a while for mdbook to adopt. Example attributes does not seem a bad solution, at least it will explicitly show edition. After select section of this book was advertised in interview, probably it would make sense to accept this so that futures examples are working while people visiting page to make good impression?

**Comment by kngwyu** [comment]
Looks run buttons are still broken and we need this PR merged.
mdbook's `edition = "2018"` is still not merged and we need annotation or patching book.js to make playpen work.

**Comment by cramertj** [comment]
This seems like a pretty painful way to specify the 2018 edition, but it seems like a lot of people are hitting this, so it seems fine to me to merge. Sorry for the wait!

**Pull request merged**
