### PR TITLE
Add missing html files

### PR DESCRIPTION
**Pull request by taiki-e**
Closes #161

### CODE REVIEW

**Comment by Apurer** [comment]
You created new pull request instead of merging mine?!

**Comment by taiki-e** [comment]
Please see diff. More HTML files were actually missing.

**Comment by Apurer** [comment]
I can see that more HTML files were missing but you could have merged mine and add the rest of missing files with your own merge. I wanted to contribute to rust repository and this way it was I won't show up in commits.

**Comment by SteveLauC** [comment]
@Apurer 
If I were the reviewer, I will say: "It seems there are some extra missing html files, would you like to also add them? Thanks!"
And you can add more commits on your pr branch, then I will merge it.

I personally think this is a better solution and more contributor-friendly

**Comment by taiki-e** [comment]
> This way I won't show up in commits.

Sorry for this! (I thought this was just copy of existing files in the repository and therefore not problematic from a view of copyright, but) I probably should have added you as a co-author of this commit.

**Pull request merged**
